### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by StevenTCramer** [jsakamoto/Toolbelt.Blazor.SplitContainer#4]
```console
dotnet new blazorserver -n SplitterTest
cd .\SplitterTest\
dotnet add package Toolbelt.Blazor.SplitContainer
```

Add the following to `_Imports.razor`
```razor
@using Toolbelt.Blazor.Splitter
```
Change `Pages/Index.razor` to 

```razor
@page "/"

<SplitContainer @bind-FirstPaneSize="_PaneSize">

    <FirstPane>
        <h1>Hello</h1>
    </FirstPane>

    <SecondPane>
        <h1>World</h1>
    </SecondPane>

</SplitContainer>

@code {
    private int _PaneSize = 80;
}
```

```console
dotnet run
```

result looks like

![image](https://user-images.githubusercontent.com/357219/217479723-5ed7e59c-4f0d-4974-a381-72e027896548.png)

**Comment by jsakamoto** [comment]
The reason why you get such a result is there is no styling for those components. The `SplitContainer` is **just a container component**, so you have to take all responsibility for its appearance, such as size, border color and style, background color, etc.

For example, if you add the CSS styles below to the end of the `wwwroot/css/site.css` file:

```css

.split-container {
    width: 100%;
    height: 320px;
}

.spliter-bar {
    background-color: blueviolet;
}

.pane-of-split-container {
    display: flex;
    justify-content: center;
    align-items: center;
    border: dashed 2px blueviolet;
}
```

Then, you will see the result in the following screenshot.

![movie-001](https://user-images.githubusercontent.com/95908/217539627-552cb2aa-b6aa-489d-a96a-f93ad070ee3a.gif)

That's all.
