### ISSUE TITLE
Selector issue for splitter-bar

### ISSUE THREAD

**Issue by ugumba** [jsakamoto/Toolbelt.Blazor.SplitContainer#6]
With a case like this:

```html
<SplitContainer Orientation=Vertical>
  <FirstPane>
    <SplitContainer Orientation=Horizontal>
      <FirstPane>
        <SplitContainer Orientation=Vertical>
          <FirstPane>
          </FirstPane>
          <SecondPane/>
        </SplitContainer>
      </FirstPane>
      <SecondPane/>
    </SplitContainer>
  </FirstPane>
  <SecondPane/>
</SplitContainer>
```
... the innermost spliter-bar shows an "up-down" cursor instead of "left-right".

I think something is wrong in SplitContainer.razor.css.  If I add ">" like the below, it looks correct in the browser, but I'm no CSS expert:

```css
.splitter-orientation-vertical > .spliter-bar {
  min-width: var(--splitter-bar-size);
  cursor: w-resize;
}
.splitter-orientation-horizontal > .spliter-bar {
  min-height: var(--splitter-bar-size);
  cursor: n-resize;
}
```
